#!/bin/sh
echo "********************************"
echo " Exec rcS "
echo "********************************"

runlevel=S
export runlevel

# Host name
/bin/hostname mcuzone

# Mount /proc if not
[ -d "/proc/1" ] || mount /proc

echo "********mount all********"
/bin/mount -av

mkdir /dev/pts
mount -t devpts devpts /dev/pts

#alsa lib hack
ln -s /dev /dev/snd

# Read the busybox docs: mdev.txt
echo "********Starting mdev********"
echo "This may take some time ..."
/bin/mount -t sysfs sysfs /sys
/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

# When mdev is mounted, /sys can be umounted
#/bin/umount /sys

# Start local services
/etc/init.d/rc.local

echo "********************************"
echo "     513 xi'an R&D Center       "
echo "                                " 
echo "   Linux For Energy Monitor     " 
echo "                                " 
echo "********************************"
ifconfig eth0 192.168.1.250
cd /app
./runapp.sh&
